// website/pages/auth/forgetPassword.tsx
import axios from 'axios';
import * as crypto from 'crypto-js';
import * as _ from 'lodash';
import { useEffect, useState, useRef } from 'react';
import { connect } from 'react-redux';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { FacebookProvider, LoginButton } from 'react-facebook';
import { compose } from 'redux';
import { useCookies } from 'react-cookie';
import { PaletteTypeEnum } from '../../enums/PaletteTypeEnum';

// mui
import Typography from '@material-ui/core/Typography';
import Paper from '@material-ui/core/Paper';
import Button from '@material-ui/core/Button';
import Container from '@material-ui/core/Container';
import Grid from '@material-ui/core/Grid';
import FacebookIcon from '@material-ui/icons/Facebook';

import { ValidatorForm, TextValidator} from 'react-material-ui-form-validator';

import { setMessage, setPaletteType, setProgressOn } from '../../store/actions/globalActions';
import { SeverityEnum } from '../../enums/SeverityEnum';

import defaultNextI18Next from '../../plugins/i18n';
const { i18n, Link, withTranslation } = defaultNextI18Next;

// components
import Layout from '../../components/layout';

function ForgetPassword ({ paletteType, dispatch, t }) {
  const [cookies, setCookie] = useCookies(['iBlog']);
  const inputForm = useRef('form');
  const [userEmail, setUserEmail] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [verifyCode, setVerifyCode] = useState('');
  const router = useRouter();


  const handleEmailChange = (event) => {
    const value = event.currentTarget.value;
    setUserEmail(value);
  }

  const handleVerifyCodeChange = (event) => {
    const value = event.currentTarget.value;
    setVerifyCode(value);
  }

  const handlePasswordChange = (event) => {
    const value = event.currentTarget.value;    
    setPassword(value);
  }

  const handleConfirmPasswordChange = (event) => {
    const value = event.currentTarget.value;
    setConfirmPassword(value);
  }

  const encryptAES = async (password: string): Promise<string> => {
    const encryptedPassword = await crypto.AES.encrypt(password, process.env.NEXT_PUBLIC_AES_SECRECT).toString();

    return encryptedPassword;
  }

  const sendVerifyCodeEmail = async () => {
    dispatch(setProgressOn(true));
    try {
      if (!userEmail) {
        dispatch(setMessage({
          open: true,
          severity: SeverityEnum.error,
          message: t(`messages.forgetPassword.form.emailRequired`)
        }));
        dispatch(setProgressOn(false));

        return
      }
      const postData = {
        email: userEmail
      }
      await axios.post(`${process.env.NEXT_PUBLIC_USER_API}/users/forgetPassword`, postData);
      
      // register success tips
      dispatch(setMessage({
        open: true,
        severity: SeverityEnum.success,
        message: t(`messages.forgetPassword.general.sendVerifyCodeSuccess`)
      }));
    } catch (err) {
      let errMessage: string;
      const message = _.get(err, 'response.data.message');
      errMessage = !!message ? t(`messages.forgetPassword.errors.${message}`) : t(`messages.common.unknownError`);
      console.log(err);
      
      // show error message
      dispatch(setMessage({
        open: true,
        severity: SeverityEnum.error,
        message: errMessage
      }));
    }
    dispatch(setProgressOn(false));
  } 

  const handleSubmit = async () => {
    dispatch(setProgressOn(true));
    try {
      const postData = {
        email: userEmail,
        verifyCode,
        password: await encryptAES(password)
      }
      await axios.post(`${process.env.NEXT_PUBLIC_USER_API}/users/resetPassword`, postData);
      
      // register success tips
      dispatch(setMessage({
        open: true,
        severity: SeverityEnum.success,
        message: t(`messages.forgetPassword.general.resetPasswordSuccess`)
      }));

      // redirect to login page
      router.push('/auth/login');
    } catch (err) {
      let errMessage: string;
      const message = _.get(err, 'response.data.message');
      errMessage = !!message ? t(`messages.forgetPassword.errors.${message}`) : t(`messages.common.unknownError`);
      console.log(err);
      
      // show error message
      dispatch(setMessage({
        open: true,
        severity: SeverityEnum.error,
        message: errMessage
      }));
    }
    dispatch(setProgressOn(false));
  }

  const init = async () => {
    if (!!cookies.paletteType) {
      dispatch(setPaletteType(cookies.paletteType));
    } else {
      setCookie('paletteType', PaletteTypeEnum.light, { path: '/' });
    }
  }

  useEffect(() => {
    init();
  }, [])

  useEffect(() => {
    ValidatorForm.removeValidationRule('isPasswordMatch');
    ValidatorForm.addValidationRule('isPasswordMatch', (value: string) => {
      if (value !== password) {
          return false;
      }
      return true;
    });
  }, [confirmPassword])

  return (
    <Layout>
      <Head>
        <title>iBlog { t('headers.forgetPasswordPage') }</title>
      </Head>
      <div className='forgetPassword'>
        <Container className="paperContainer" maxWidth="xs">
        <Paper className='paperStyle'>
              <Container>
                <ValidatorForm
                  ref={inputForm}
                  onSubmit={handleSubmit}
                >
                  <Grid container spacing={2}>
                    <Grid item xs={12} style={{ textAlign: "center" }}>
                      <Typography variant="h6" noWrap>
                        {t('pages.forgetPassword.iblogResetPassword')}
                      </Typography>
                    </Grid>
                    <Grid item xs={12}>
                      <Typography variant="subtitle2" noWrap>
                      {t('pages.forgetPassword.email')}
                      </Typography>
                      <TextValidator
                        name="userEmail"
                        value={userEmail}
                        variant="outlined"
                        fullWidth
                        validators={['required', 'isEmail']}
                        onChange={handleEmailChange}
                        errorMessages={[t('messages.forgetPassword.form.emailRequired'), t('messages.forgetPassword.form.emailNotValid')]}
                      />
                    </Grid>
                    <Grid item xs={6}>
                      <Grid container alignItems="center" style={{ height: '100%' }}>
                        <Button 
                          variant="contained"
                          type="button"
                          onClick={sendVerifyCodeEmail}
                          color={ paletteType === PaletteTypeEnum.light ? 'primary' : 'default' }
                        >
                          {t('pages.forgetPassword.getVerifyCode')}
                        </Button>
                      </Grid>
                    </Grid>
                    <Grid item xs={6}>
                      <Typography variant="subtitle2" noWrap>
                      {t('pages.forgetPassword.verifyCode')}
                      </Typography>
                      <TextValidator
                        name="verifyCode"
                        value={verifyCode}
                        variant="outlined"
                        fullWidth
                        validators={['required']}
                        onChange={handleVerifyCodeChange}
                        errorMessages={[t('messages.forgetPassword.form.verifyCodeRequired')]}
                      />
                    </Grid>
                    <Grid item xs={12}>
                      <Typography variant="subtitle2" noWrap>
                        {t('pages.forgetPassword.password')}
                      </Typography>
                      <TextValidator
                        name="password"
                        value={password}
                        variant="outlined"
                        type='password'
                        fullWidth
                        validators={['required']}
                        onChange={handlePasswordChange}
                        errorMessages={[t('messages.forgetPassword.form.passwordRequired')]}
                      />
                    </Grid>
                    <Grid item xs={12}>
                      <Typography variant="subtitle2" noWrap>
                        {t('pages.forgetPassword.confirmPassword')}
                      </Typography>
                      <TextValidator
                        name="repeatPassword"
                        value={confirmPassword}
                        variant="outlined"
                        type='password'
                        fullWidth
                        validators={['isPasswordMatch', 'required']}
                        onChange={handleConfirmPasswordChange}
                        errorMessages={[t('messages.forgetPassword.form.passwordMissmatch'), t('messages.forgetPassword.form.confirmPasswordRequired')]}
                      />
                    </Grid>
                    <Grid item xs={12}>
                      <Button 
                        variant="contained"
                        type="submit"
                        fullWidth
                        color={ paletteType === PaletteTypeEnum.light ? 'primary' : 'default' }
                      >
                        {t('pages.login.submit')}
                      </Button>
                    </Grid>
                    <Grid item xs={12} style={{ textAlign: "center", marginTop: '40px' }}>
                      <Link href="/auth/login">
                        <span style={{ cursor: "pointer" }}>{t('pages.forgetPassword.backToLogin')}</span>
                      </Link>
                    </Grid>
                  </Grid>
                </ValidatorForm>
              </Container>
            </Paper>
        </Container>
      </div>
    </Layout>
  )
}

const mapStateToProps = (state) => {
  const { global } = state;
  return {
    paletteType: global && global.paletteType || PaletteTypeEnum.light
  }
}

ForgetPassword.getInitialProps = async () => ({
  namespacesRequired: ['common'],
})

export default compose<any>(
  connect(mapStateToProps),
  withTranslation('common')
)(ForgetPassword)

// web/pages/auth/forgetPassword.vue
<template>
    <div class="forgetPassword">
        <AppBar />
        <v-container class="mt-5" :style="`max-width: ${thresholds.xs}px`">
            <v-sheet color="defualt" elevation="1" rounded>
                <div class="pa-5">
                    <v-form ref="forgetPasswordForm" v-model="valid" lazy-validation>
                        <div class="forgetPasswordFormTitle title-1">iBlog {{ $t('headers.forgetPasswordPage') }}</div>
                        <div class="title-2 mt-8">{{ $t('pages.forgetPassword.email') }}</div>
                        <v-text-field v-model="email" :rules="emailRules" outlined dense :error-messages="emailRequiredMessage"></v-text-field>
                        <div class="title-2">{{ $t('pages.forgetPassword.verifyCode') }}</div>
                        <div class="verifyCodeContainer">
                            <div style="width: 50%">
                                <v-text-field v-model="verifyCode" :rules="verifyCodeRules" outlined dense></v-text-field>
                            </div>
                            <v-btn @click="sendVerifyCodeEmail" :color="secondaryColor">{{ $t('pages.forgetPassword.getVerifyCode') }}</v-btn>
                        </div>
                        <div class="title-2">{{ $t('pages.forgetPassword.password') }}</div>
                        <v-text-field v-model="password" :rules="passwordRules" outlined dense type="password" />
                        <div class="title-2">{{ $t('pages.forgetPassword.confirmPassword') }}</div>
                        <v-text-field v-model="confirmPassword" :rules="confirmPasswordRules" outlined dense type="password" />
                        <div class="my-8">
                            <v-btn @click="sumbitLoginForm" :color="primaryColor" block>{{ $t('pages.common.submit') }}</v-btn>
                        </div>
                        <div style="text-align: center">
                            <span @click="redirectToLogin" style="cursor: pointer">{{$t('pages.forgetPassword.backToLogin')}}</span>
                        </div>
                    </v-form>
                </div>
            </v-sheet>
        </v-container>
    </div>
</template>
<script>
    import * as crypto from 'crypto-js';
    import * as _ from 'lodash';
    import AppBar from '../../components/appBar';

    export default {
        data() {
            return {
                thresholds: this.$vuetify.breakpoint.thresholds,
                valid: true,
                email: '',
                emailRules: [
                    v => !!v || this.$t('messages.forgetPassword.form.emailRequired'),
                    v => /.+@.+\..+/.test(v) || this.$t('messages.forgetPassword.form.emailNotValid'),
                ],
                emailRequiredMessage: null,
                verifyCode: '',
                verifyCodeRules: [
                    v => !!v || this.$t('messages.forgetPassword.form.verifyCodeRequired')
                ],
                password: '',
                passwordRules: [
                    v => !!v || this.$t('messages.forgetPassword.form.passwordRequired')
                ],
                confirmPassword: ''
            }
        },
        components: { AppBar },
        methods: {
            async encryptAES (password) {
                const encryptedPassword = await crypto.AES.encrypt(password, process.env.aesSecrect).toString();

                return encryptedPassword;
            },
            async sumbitLoginForm() {
                if (!this.$refs.forgetPasswordForm.validate()) return
                this.$store.dispatch('global/setProgressBar', { progressBar: true });
                try {
                    const postData = {
                        email: this.email,
                        verifyCode: this.verifyCode,
                        password: await this.encryptAES(this.password)
                    }
                    await this.$axios.post(`${process.env.userApi}/users/resetPassword`, postData);

                    // update password success tips
                    this.$store.dispatch('global/setSnackBar', {
                        snackBar: {
                            open: true,
                            color: 'success',
                            message: this.$t(`messages.forgetPassword.general.resetPasswordSuccess`)
                        }
                    });

                    this.redirectToLogin();
                } catch (err) {
                    let errMessage;
                    const message = _.get(err, 'response.data.message');
                    errMessage = !!message ? this.$t(`messages.forgetPassword.errors.${message}`) : this.$t(`messages.common.unknownError`);

                    // show error message
                    this.$store.dispatch('global/setSnackBar', {
                        snackBar:{
                            open: true,
                            color: 'error',
                            message: errMessage
                        }
                    });
                }
                this.$store.dispatch('global/setProgressBar', { progressBar: false });
            },
            async sendVerifyCodeEmail() {
                if (!this.email) {
                    this.emailRequiredMessage = this.$t('messages.forgetPassword.form.emailRequired');
                    return
                }
                // not an email
                if (!/.+@.+\..+/.test(this.email)) {
                    this.emailRequiredMessage = this.$t('messages.forgetPassword.form.emailNotValid');
                    return
                }
                this.$store.dispatch('global/setProgressBar', { progressBar: true });
                try {
                    const postData = {
                        email: this.email
                    }
                    await this.$axios.post(`${process.env.userApi}/users/forgetPassword`, postData);

                    // email sent success tips
                    this.$store.dispatch('global/setSnackBar', {
                        snackBar: {
                            open: true,
                            color: 'success',
                            message: this.$t(`messages.forgetPassword.general.sendVerifyCodeSuccess`)
                        }
                    });
                } catch (err) {
                    let errMessage;
                    const message = _.get(err, 'response.data.message');
                    errMessage = !!message ? this.$t(`messages.forgetPassword.errors.${message}`) : this.$t(`messages.common.unknownError`);

                    // show error message
                    this.$store.dispatch('global/setSnackBar', {
                        snackBar:{
                            open: true,
                            color: 'error',
                            message: errMessage
                        }
                    });
                }
                this.$store.dispatch('global/setProgressBar', { progressBar: false });
            },
            redirectToLogin() {
                this.$router.push({
                    name: `auth-login___${this.$i18n.locale}`
                })
            }
        },
        computed: {
            primaryColor() {
                return this.$store.state.mode.mode === 'light' ? 'primary' : 'default';
            },
            secondaryColor() {
                return this.$store.state.mode.mode === 'light' ? 'secondary' : 'primary';
            },
            confirmPasswordRules() {
                return [
                    !!this.confirmPassword || this.$t('messages.forgetPassword.form.confirmPasswordRequired'),
                    this.confirmPassword === this.password || this.$t('messages.forgetPassword.form.passwordMissmatch')
                ]
            }
        },
        watch: {
            email() {
                this.emailRequiredMessage = null;
            }
        },
        head() {
            return {
                title: this.$t('headers.forgetPasswordPage')
            }
        }
    }
</script>
