// web/pages/auth/register.vue
<template>
    <div class="register">
        <AppBar />
        <v-container class="mt-5" :style="`max-width: ${thresholds.xs}px`">
            <div v-if="verifyCode && verifyEmail">
                <div v-if="verifying">{{ $t(`messages.register.general.activatingAccount`) }}</div>
                <div v-else>{{ $t(`messages.register.errors.activateFail`) }}</div>
            </div>
            <v-sheet v-else color="defualt" elevation="1" rounded>
                <div class="pa-5">
                    <v-form ref="registerForm" v-model="valid" lazy-validation>
                        <div class="registerFormTitle title-1">iBlog {{ $t('headers.registerPage') }}</div>
                        <div class="title-2 mt-8">{{ $t('pages.register.username') }}</div>
                        <v-text-field v-model="username" :rules="usernameRules" outlined dense></v-text-field>
                        <div class="title-2">{{ $t('pages.register.email') }}</div>
                        <v-text-field v-model="email" :rules="emailRules" outlined dense :error-messages="emailRequiredMessage"></v-text-field>
                        <div class="title-2">{{ $t('pages.register.password') }}</div>
                        <v-text-field v-model="password" :rules="passwordRules" outlined dense type="password" />
                        <div class="title-2">{{ $t('pages.register.confirmPassword') }}</div>
                        <v-text-field v-model="confirmPassword" :rules="confirmPasswordRules" outlined dense type="password" />
                        <div class="my-8">
                            <v-btn @click="sumbitLoginForm" :color="primaryColor" block>{{ $t('pages.common.submit') }}</v-btn>
                        </div>
                        <div style="text-align: center">
                            <span @click="redirectToLogin" style="cursor: pointer">{{$t('pages.register.alreadyHaveAccount')}}</span>
                        </div>
                    </v-form>
                </div>
            </v-sheet>
        </v-container>
    </div>
</template>
<script>
    import * as crypto from 'crypto-js';
    import * as _ from 'lodash';
    import AppBar from '../../components/appBar';

    export default {
        data() {
            return {
                thresholds: this.$vuetify.breakpoint.thresholds,
                valid: true,
                verifying: true,
                verifyEmail: this.$route.query.email,
                verifyCode: this.$route.query.verifyCode,
                username: '',
                usernameRules: [
                    v => !!v || this.$t('messages.register.form.usernameRequired')
                ],
                email: '',
                emailRules: [
                    v => !!v || this.$t('messages.forgetPassword.form.emailRequired'),
                    v => /.+@.+\..+/.test(v) || this.$t('messages.forgetPassword.form.emailNotValid'),
                ],
                emailRequiredMessage: null,
                password: '',
                passwordRules: [
                    v => !!v || this.$t('messages.forgetPassword.form.passwordRequired')
                ],
                confirmPassword: ''
            }
        },
        components: { AppBar },
        methods: {
            async encryptAES (password) {
                const encryptedPassword = await crypto.AES.encrypt(password, process.env.aesSecrect).toString();

                return encryptedPassword;
            },
            async sumbitLoginForm() {
                if (!this.$refs.registerForm.validate()) return
                this.$store.dispatch('global/setProgressBar', { progressBar: true });
                try {
                    const postData = {
                        username: this.username,
                        email: this.email,
                        password: await this.encryptAES(this.password)
                    }
                    await this.$axios.post(`${process.env.userApi}/users/register`, postData);

                    // send register email success tips
                    this.$store.dispatch('global/setSnackBar', {
                        snackBar: {
                            open: true,
                            color: 'success',
                            message: this.$t(`messages.register.general.registerSuccess`)
                        }
                    });

                    this.redirectToLogin();
                } catch (err) {
                    let errMessage;
                    const message = _.get(err, 'response.data.message');
                    errMessage = !!message ? this.$t(`messages.register.errors.${message}`) : this.$t(`messages.common.unknownError`);

                    // show error message
                    this.$store.dispatch('global/setSnackBar', {
                        snackBar:{
                            open: true,
                            color: 'error',
                            message: errMessage
                        }
                    });
                }
                this.$store.dispatch('global/setProgressBar', { progressBar: false });
            },
            async registerVerify() {
                this.$store.dispatch('global/setProgressBar', { progressBar: true });
                try {
                    const postData = {
                        email: this.verifyEmail,
                        verifyCode: this.verifyCode
                    }
                    await this.$axios.post(`${process.env.userApi}/users/registerVerify`, postData);

                    // verify email success tips
                    this.$store.dispatch('global/setSnackBar', {
                        snackBar: {
                            open: true,
                            color: 'success',
                            message: this.$t(`messages.register.general.activateSuccess`)
                        }
                    });

                    this.redirectToLogin();
                } catch (err) {
                    let errMessage;
                    const message = _.get(err, 'response.data.message');
                    errMessage = !!message ? this.$t(`messages.register.errors.${message}`) : this.$t(`messages.common.unknownError`);

                    this.verifying = false;  // control showing verifying fail message

                    // show error message
                    this.$store.dispatch('global/setSnackBar', {
                        snackBar:{
                            open: true,
                            color: 'error',
                            message: errMessage
                        }
                    });
                }
                this.$store.dispatch('global/setProgressBar', { progressBar: false });
            },
            redirectToLogin() {
                this.$router.push({
                    name: `auth-login___${this.$i18n.locale}`
                })
            }
        },
        computed: {
            primaryColor() {
                return this.$store.state.mode.mode === 'light' ? 'primary' : 'default';
            },
            secondaryColor() {
                return this.$store.state.mode.mode === 'light' ? 'secondary' : 'primary';
            },
            confirmPasswordRules() {
                return [
                    !!this.confirmPassword || this.$t('messages.forgetPassword.form.confirmPasswordRequired'),
                    this.confirmPassword === this.password || this.$t('messages.forgetPassword.form.passwordMissmatch')
                ]
            }
        },
        async beforeMount() {
            if (this.verifyEmail && this.verifyCode) {
                await this.registerVerify();
            }
        },
        head() {
            return {
                title: this.$t('headers.registerPage')
            }
        }
    }
</script>

// website/pages/auth/register.tsx
import axios from 'axios';
import * as crypto from 'crypto-js';
import * as _ from 'lodash';
import { useEffect, useState, useRef } from 'react';
import { connect } from 'react-redux';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { compose } from 'redux';
import { useCookies } from 'react-cookie';
import { PaletteTypeEnum } from '../../enums/PaletteTypeEnum';

// mui
import Typography from '@material-ui/core/Typography';
import Paper from '@material-ui/core/Paper';
import Button from '@material-ui/core/Button';
import Container from '@material-ui/core/Container';
import Grid from '@material-ui/core/Grid';

import { ValidatorForm, TextValidator} from 'react-material-ui-form-validator';

import { setMessage, setPaletteType, setProgressOn } from '../../store/actions/globalActions';
import { SeverityEnum } from '../../enums/SeverityEnum';

import defaultNextI18Next from '../../plugins/i18n';
const { i18n, Link, withTranslation } = defaultNextI18Next;

// components
import Layout from '../../components/layout';

function Register({ paletteType, dispatch, t }) {
  const [cookies, setCookie] = useCookies(['iBlog']);
  const inputForm = useRef('form');
  const [username, setUsername] = useState('');
  const [userEmail, setUserEmail] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [verifying, setVerifying] = useState(true);

  const passwordRef = useRef(password);
  passwordRef.current = password;
  const router = useRouter();
  const { email, verifyCode } = router.query;

  const handleUsernameChange = (event) => {
    const value = event.currentTarget.value;
    setUsername(value);
  }

  const handleEmailChange = (event) => {
    const value = event.currentTarget.value;
    setUserEmail(value);
  }

  const handlePasswordChange = (event) => {
    const value = event.currentTarget.value;    
    setPassword(value);
  }

  const handleConfirmPasswordChange = (event) => {
    const value = event.currentTarget.value;
    setConfirmPassword(value);
  }

  const encryptAES = async (password: string): Promise<string> => {
    const encryptedPassword = await crypto.AES.encrypt(password, process.env.NEXT_PUBLIC_AES_SECRECT).toString();

    return encryptedPassword;
  }

  const handleSubmit = async () => {
    dispatch(setProgressOn(true));
    try {
      const postData = {
        username,
        email: userEmail,
        password: await encryptAES(password)
      }
      await axios.post(`${process.env.NEXT_PUBLIC_USER_API}/users/register`, postData);
      
      // register success tips
      dispatch(setMessage({
        open: true,
        severity: SeverityEnum.success,
        message: t(`messages.register.general.registerSuccess`)
      }));

      // redirect to login page
      router.push('/auth/login');
    } catch (err) {
      let errMessage: string;
      const message = _.get(err, 'response.data.message');
      errMessage = !!message ? t(`messages.register.errors.${message}`) : t(`messages.common.unknownError`);
      
      // show error message
      dispatch(setMessage({
        open: true,
        severity: SeverityEnum.error,
        message: errMessage
      }));
    }
    dispatch(setProgressOn(false));
  }

  const registerVerify = async () => {
    dispatch(setProgressOn(true));
      try {
        const postData = {
          email,
          verifyCode
        }
        await axios.post(`${process.env.NEXT_PUBLIC_USER_API}/users/registerVerify`, postData);

        dispatch(setMessage({
          open: true,
          severity: SeverityEnum.success,
          message: t(`messages.register.general.activateSuccess`)
        }));
        
        // redirect to login page
        router.push('/auth/login');
      } catch (err) {
        const message = _.get(err, 'response.data.message');
        const errMessage = !!message ? t(`messages.register.errors.${message}`) : t(`messages.common.unknownError`);

        // show error message
        dispatch(setMessage({
          open: true,
          severity: SeverityEnum.error,
          message: errMessage
        }));
          
        setVerifying(false);
      }
    dispatch(setProgressOn(false));
  }

  const init = async () => {
    if (!!email && !!verifyCode) {
      registerVerify();
    }
    ValidatorForm.addValidationRule('isPasswordMatch', (value: string) => {
      if (value !== passwordRef.current) {
          return false;
      }
      return true;
    });
  }

  useEffect(() => {
    init();
    return () => ValidatorForm.removeValidationRule('isPasswordMatch');
  }, []);

  return (
    <Layout>
      <Head>
        <title>iBlog { t('headers.registerPage') }</title>
      </Head>
      <div className='register'>
        <Container className="paperContainer" maxWidth="xs">
          {
            !!email && !!verifyCode &&
            <div className="pageMeassage">
              { verifying ? t(`messages.register.general.activatingAccount`) : t(`messages.register.errors.activateFail`) }
            </div>
          }
          {
            !(email && verifyCode) &&
            <Paper className='paperStyle'>
              <Container>
                <ValidatorForm
                  ref={inputForm}
                  onSubmit={handleSubmit}
                >
                  <Grid container spacing={2}>
                    <Grid item xs={12} style={{ textAlign: "center" }}>
                      <Typography variant="h6" noWrap>
                        {t('pages.register.iblogRegister')}
                      </Typography>
                    </Grid>
                    <Grid item xs={12}>
                      <Typography variant="subtitle2" noWrap>
                      {t('pages.register.username')}
                      </Typography>
                      <TextValidator
                        name="username"
                        value={username}
                        variant="outlined"
                        fullWidth
                        validators={['required']}
                        onChange={handleUsernameChange}
                        errorMessages={[t('messages.register.form.usernameRequired')]}
                      />
                    </Grid>
                    <Grid item xs={12}>
                      <Typography variant="subtitle2" noWrap>
                      {t('pages.register.email')}
                      </Typography>
                      <TextValidator
                        name="email"
                        value={userEmail}
                        variant="outlined"
                        fullWidth
                        validators={['required', 'isEmail']}
                        onChange={handleEmailChange}
                        errorMessages={[t('messages.register.form.emailRequired'), t('messages.register.form.emailNotValid')]}
                      />
                    </Grid>
                    <Grid item xs={12}>
                      <Typography variant="subtitle2" noWrap>
                        {t('pages.register.password')}
                      </Typography>
                      <TextValidator
                        name="password"
                        value={password}
                        variant="outlined"
                        type='password'
                        fullWidth
                        autoComplete='false'
                        validators={['required']}
                        onChange={handlePasswordChange}
                        errorMessages={[t('messages.register.form.passwordRequired')]}
                      />
                    </Grid>
                    <Grid item xs={12}>
                      <Typography variant="subtitle2" noWrap>
                        {t('pages.register.confirmPassword')}
                      </Typography>
                      <TextValidator
                        name="repeatPassword"
                        value={confirmPassword}
                        variant="outlined"
                        type='password'
                        fullWidth
                        autoComplete='false'
                        validators={['isPasswordMatch', 'required']}
                        onChange={handleConfirmPasswordChange}
                        errorMessages={[t('messages.register.form.passwordMissmatch'), t('messages.register.form.confirmPasswordRequired')]}
                      />
                    </Grid>
                    <Grid item xs={12}>
                      <Button 
                        variant="contained"
                        type="submit"
                        fullWidth
                        color={ paletteType === PaletteTypeEnum.light ? 'primary' : 'default' }
                      >
                        {t('pages.login.submit')}
                      </Button>
                    </Grid>
                    <Grid item xs={12} style={{ textAlign: "center", marginTop: '40px' }}>
                      <Link href="/auth/login">
                        <span style={{ cursor: "pointer" }}>{t('pages.register.alreadyHaveAccount')}</span>
                      </Link>
                    </Grid>
                  </Grid>
                </ValidatorForm>
              </Container>
            </Paper>
          }
        </Container>
      </div>
    </Layout>
  )
}

const mapStateToProps = (state) => {
  const { global } = state;
  return {
    paletteType: global && global.paletteType || PaletteTypeEnum.light
  }
}

Register.getInitialProps = async () => ({
  namespacesRequired: ['common'],
})

export default compose<any>(
  connect(mapStateToProps),
  withTranslation('common')
)(Register)
